---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="sirspock"
  matrix:
    - image="centos" tag="7"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="ubuntu" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all
